language: node_js
<<<<<<< HEAD
node_js:
- 4.0
- 6.0
before_deploy:
- test $TRAVIS_TEST_RESULT = 0
before_install:
- npm install -g mocha
deploy:
- provider: script    # (If version.txt is updated) - create a new tag and push to Github, update the latest-release branch
  script: ./create-release.sh
  on: master
  # Automatic deploys are enabled in Heroku for this app
  # Every push to master will deploy a new version of this app. Deploys happen automatically.
  # Heroku will wait for CI to pass before deploying.
notifications:
  email: false
sudo: false
env:
  global:
  - secure: esj3ut+TwKX25QzU1koJyTVIX+x1V55graI65X8LiYXKcOP040VPJ9lIC0HeRs5UViBM0Ur1F93rGdgW2zYVzu5MLZoH7KjpzMcG30x+FDqLChT0JfNcLLtLm/wIhx/OAAmsBxXlvjPp092BeEKd3Jug8d329TxwwK5G5XxAatg=
=======

node_js:
  - "lts/*"
  - "8"

os:
  - linux
  - osx
  - windows

jobs:
  include:
    # If version.txt is updated on the master branch:
    # - create a new tag and push it to Github
    # - update the latest-release branch
    - stage: deploy
      name: "Create release on GitHub 🚀"
      os: linux
      script: echo "Checking whether we should release..."
      deploy:
      - provider: script
        script: ./create-release.sh
        on:
          branch: master
      env:
      # DEPLOY_KEY
      - secure: qpuH/3v+wsMLy9C3bGjallB6KxFQAtDlyZf3jmX8UQ0703tIvBnZoC1h9EJXOqxZbirLPHon7g902nOuhqUfrsPQgV7XEmXMGZsp31PuK/1lkyTCG3fAdeg8wcghwZn10Gw8jYZpOfWIf2GPDL+6utIU6Aog+odcls7tHWLVT80=

# Automatic deploys are also enabled in Heroku for this app
# Every push to master will automatically deploy a new version of this app.
# Heroku will wait for CI to pass before deploying.

notifications:
  email: false

sudo: false
>>>>>>> 7dfe394cc9d3042db4ebabfd67b35a61c3048f95
