version: "3.1"

services:
  web:
    image: node:lts
    container_name: beis-par-proto
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    command: bash -c "npm install && npm start"
